---
title: "Bio"
---

My name is Ed (officially Edward Anton Rubin), and I live in Berkeley, California with my amazing wife, [Shelley](http://www.yourwritinghelper.com), and our awesome son, [Theo](http://teamrubin.us). I'm currently a doctoral candidate in the Department of Agricultural and Resource Economics at UC Berkeley. Before coming to Berkeley, Shelley and I lived in the great town of Lincoln, Nebraska.

When I'm not in school, I enjoy exploring both rural and urban places. I love data, maps, Truth, Beauty, and food.

Other pages on this website contain [random things I like](likes.html), [useful/interesting links I've found](links.html), [my research interests](researchinterests), and some of [my recent photography](https://instagram.com/edwardarubin/).

<br>

## Contact

- __email:__ edward `ampersat` berkeley `period` edu
- __twitter:__ [\@edrubin](https://twitter.com/edrubin)
- __phone:__ (4`oh`2) 3`oh`5-85`six`3
- __instagram:__ [\@edwardarubin](https://instagram.com/edwardarubin/)
