---
title: "Efficiently mapping with `ggplot2`"
output:
  html_document:
    toc: true
    number_sections: false
    toc_float:
      collapsed: false
      smooth_scroll: true
---

Sunday, 06 August 2017

<br>

## Motivation

If you have used R to make maps—particularly `ggplot2`—then you have likely noticed R can really slow down when it comes to printing larger shapefiles (be it printing to screen or saving to a file). I recently came across an excellent tool for speeding up this process substantially: the R package `rmapshaper`, which is based upon the [mapshaper.org](http://mapshaper.org) website.

## Shapefiles

If you are not super familiar with these _shapefile_ objects, the main thing to keep in mind is that a shapefile is simply a collection of points. If you have a shapefile of US counties, then the individual points jointly compose polygons. The polygons jointly make up the countries. The order and the grouping of these points matter. You can also have simpler shapefiles that represent lines or point, rather than polygons. If you need/want to learn more, there are many online resources. You can also check out my notes from a course I GSIed at Berkeley.


# Setup ----
# Options
options(stringsAsFactors = F)
# Load packages
library(pacman)
p_load(rgdal, broom, rgeos, maptools, rmapshaper,
  magrittr, lubridate, ggplot2, viridis)

# Set working directory
setwd("/Users/edwardarubin/Dropbox/Research/")
setwd("MyProjects/NaturalGas/DataSpatial/cb_2015_us_state_20m")

# Get shapefile ----
# Download/load US shapefile
# TODO
us_shp <- readOGR(dsn = ".", layer = "cb_2015_us_state_20m")
# Remove Alaska, Hawaii, and Puerto Rico
us_shp %<>% subset(!(STUSPS %in% c("AK", "HI", "PR")))

# Shapefile work ----
# Simplify the shapefile with 'ms_simplify', keeping 5%
us05_shp <- ms_simplify(us_shp, keep = 0.05, keep_shapes = T)
# Simplify the shapefile with 'ms_simplify', keeping 10%
us10_shp <- ms_simplify(us_shp, keep = 0.10, keep_shapes = T)
# Simplify the shapefile with 'ms_simplify', keeping 25%
us25_shp <- ms_simplify(us_shp, keep = 0.25, keep_shapes = T)

# Convert shapefiles to dataframes ----
# 'tidy' each of the shapefiles for plotting with 'ggplot'
us05_dt <- tidy(us05_shp, region = "GEOID")
us10_dt <- tidy(us10_shp, region = "GEOID")
us25_dt <- tidy(us25_shp, region = "GEOID")
us_dt <- tidy(us_shp, region = "GEOID")
# Compare the dimensions of each tidied shapefile
lapply(
  X = list(us05_dt, us10_dt, us25_dt, us_dt),
  FUN = dim)

# Plot ----
ggplot() +
  geom_path(data = us_dt, color = viridis(4)[1],
    aes(x = long, y = lat, group = group)) +
  geom_path(data = us25_dt, color = viridis(4)[2],
    aes(x = long, y = lat, group = group)) +
  geom_path(data = us10_dt, color = viridis(4)[3],
    aes(x = long, y = lat, group = group)) +
  geom_path(data = us05_dt, color = viridis(4)[4],
    aes(x = long, y = lat, group = group)) +
  theme_minimal()
