---
title: "Edward A. Rubin, CV"
toc: true
toc-location: left
---

<head>
<script>
  document.title = "Ed Rubin: CV";
</script>
</head>

```{=html}
<style>
  h2, h3, h4, h5, h6 {
    text-transform: lowercase;
  }
  .sidebar {
    text-transform: lowercase;
  }
</style>
```

[PDF](cv-edward-rubin.pdf)

## Academic positions

Assistant Professor, University of Oregon, Department of Economics, 2018–present

## Education

<br>Ph.D. Agricultural and Resource Economics, UC Berkeley, 2018
<br>*Committee:* [Maximilian Auffhammer](https://www.auffhammer.com), [Meredith Fowlie](https://www.meredithfowlie.com/), [Reed Walker](https://w-reed-walker.com)
<br>M.S. Agricultural and Resource Economics, UC Berkeley, 2015
<br>M.S. Statistics, University of Nebraska–Lincoln, 2013
<br>M.S. Agricultural Economics, University of Nebraska–Lincoln, 2013
<br>B.S. Mathematics, University of Nebraska–Lincoln, 2007

__Primary interests__: Environmental Econ., Applied Econometrics/Data Science, Inequality
<br>__Secondary interests__: Health, Development, Criminal Justice

## Publications

__[Glyphosate exposure and GM seed rollout unequally reduced perinatal health](https://www.pnas.org/doi/10.1073/pnas.2413013121)__
<br> Emmett Reynier and Edward Rubin. 2025. _Proceedings of the National Academy of Sciences (USA)_. 122(3).

__[The strategic local geography of US electricity emissions](Papers/draft-plant-locations.pdf)__
<br> John Morehouse and Edward Rubin. (_Accepted_). _Journal of the Association of Environmental and Resource Economists._

__[Customer Discrimination in the Workplace: Evidence from Online Sales](Papers/draft-gender-bias.pdf)__
<br> Erin Kelley, Gregory Lane, Matthew Pecenco, and Edward Rubin. (_Accepted_). _Journal of Labor Economics_.

__[Strategic Shutdowns of Air Quality Monitors: Evidence from Jersey City and Across the U.S.](Papers/draft-strategic-monitoring.pdf)__
<br> Yingfei Mu, Edward Rubin, and Eric Zou. 2024. _[The Review of Economics and Statistics](https://doi.org/10.1162/rest_a_01477)_.

__[Quantifying heterogeneity in the price elasticity of residential natural gas](Papers/draft-natural-gas.pdf)__
<br> Edward Rubin and Maximilian Auffhammer. 2024. _[Journal of the Association of Environmental and Resource Economists](https://www.journals.uchicago.edu/doi/full/10.1086/726017)_. 11(2).

__[The Economic Impact of Critical Habitat Designation: Evidence from Vacant-Land Transactions](https://muse.jhu.edu/article/753055)__
<br> Maximilian Auffhammer, Maya Duru, Edward Rubin, and David L. Sunding. 2020. _Land Economics_, 96(2), 188–206.

__[Bringing Satellite-Based Air-Quality Estimates Down to Earth](https://www.aeaweb.org/articles?id=10.1257/pandp.20191064)__
<br> Meredith Fowlie, Edward Rubin, and Reed Walker. 2019. _AEA Papers and Proceedings_, 109: 283-88.

(Book) __[Data Science for Public Policy](https://www.springer.com/gp/book/9783030713515)__
<br> Jeffrey Chen, Edward Rubin, and Gary Cornwall. 2021. _Springer_.

## Working papers

__[Gun policy and the steel paradox: *Evidence from Oregunians*](Papers/draft-oreguns.pdf)__
<br> Katie Bollman, Benjamin Hansen, Edward Rubin, and Garrett Stanford
<br>_Revise & resubmit, Journal of Public Economics_

__[When we change the clock, does the clock change us?](Papers/draft-time.pdf)__
<br> Patrick Baylis, Severin Borenstein, and Edward Rubin

__[Who flees wildfire smoke? Income and racial disparities in temporary relocation](Papers/draft-smoke.pdf)__
<br> M. Steven Holloway and Edward Rubin

__[What can we machine learn (too much of) in 2SLS? Insights from a bias decomposition](Papers/draft-mliv.pdf)__
<br> Connor Lennon, Edward Rubin, and Glen Waddell

## Selected research in progress

__Declining power-plant emissions, co-benefits, and regulatory rebound__
<br> Edward Rubin and Meredith Fowlie

__Environmental prediction for diverse policy contexts__
<br> Andrew Dickinson and Edward Rubin

__Are our hopes too high? Testing cannabis legalization's potential to reduce criminalization__
<br> Edward Rubin

__Do aerially applied pesticides affect local air quality? Empirical evidence from California's San Joaquin Valley__
<br> Edward Rubin

__Correlated exposures__
<br> Pilar Mullican and Edward Rubin

__Mismeasurement in exposure and access: Insights from cellphone data__
<br> Edward Rubin

__How salient are environmental risks? The short- and long-run effects of lead exposure in piped water__
<br> Edward Rubin

## Teaching

__[EC607: Econometrics (III): Causal inference](https://github.com/edrubin/EC525S19)__

- University of Oregon: [Spring 2024](https://github.com/edrubin/EC607S24), [Spring 2023](https://github.com/edrubin/EC607S23), [Spring 2022](https://github.com/edrubin/EC607S22), [Spring 2021](https://github.com/edrubin/EC607S21), [Spring 2020](https://github.com/edrubin/EC607S20), [Spring 2019](https://github.com/edrubin/EC525S19)
- Doctoral course; advanced causal-inference methods.

__[EC524: Econometrics (II): Prediction and machine learning](https://github.com/edrubin/EC524W20)__

- University of Oregon: [Winter 2025](https://github.com/edrubin/EC524W25), [Spring 2024](https://github.com/edrubin/EC524S24), [Winter 2023](https://github.com/edrubin/EC524W23), [Winter 2022](https://github.com/edrubin/EC524W22), [Winter 2021](https://github.com/edrubin/EC524W21); [Winter 2020](https://github.com/edrubin/EC524W20)
- Masters course; key machine learning methods across diverse prediction contexts.

__[EC421: Introduction to Econometrics (II)](https://github.com/edrubin/EC421S19)__

- University of Oregon: [Winter 2025](https://github.com/edrubin/EC421W25), Spring 2023, Winter 2023, Spring 2022, [Winter 2022](https://github.com/edrubin/EC421W22), [Winter 2021](https://github.com/edrubin/EC421W21); [Spring 2020](https://github.com/edrubin/EC421S20); [Winter 2020](https://github.com/edrubin/EC421W20); [Spring 2019](https://github.com/edrubin/EC421S19); [Winter 2019](https://github.com/edrubin/EC421W19)
- Undergrad. course; foundational topics in regression, visualization, time-series, causal-inference methods.

__[ARE 212: Econometrics - Multiple Equation Estimation](https://edrub.in/ARE212)__

- University of California, Berkeley: Spring 2017, Spring 2018
- Doctoral course; taught recitation section and built [section website/notes](http://edrub.in/ARE212/).

__STAT 380: Statistics and Applications__

- University of Nebraska–Lincoln: Summer 2012, Fall 2012, Spring 2013
- Undergraduate course; intermediate statistics.

__STAT 218: Introduction to Statistics__

- University of Nebraska–Lincoln: Spring 2011, Summer 2011, Fall 2011
- Undergraduate course; introductory statistics.

## Grants, awards, etc.

(Grant) __International Growth Centre__ with Anshuman Tiwari and Shefali Khanna, _The Heterogeneous Impacts of Air Pollution on Workers_, £18,842

(Grant) __Arnold Ventures__ with Benjamin Hansen, _Marijuana and the Minimum Legal Purchase Age_, 2025–2027 , $298,951

(Grant) __US EPA__ with Meredith Fowlie, _A Retrospective Analysis of Indirect Air Quality Benefits from Power-Sector Emissions Reductions_, 2021, $24,919

(Grant) __Alfred P. Sloan Foundation__, [_The Workshop for Environmental Economics and Data Science_](https://tweeds.io), 2020–2022, $30,000

(Grant) __University of Oregon Data-Science Initiative Seed Funding__, [_The Workshop for Environmental Economics and Data Science_](https://tweeds.io), 2019–2020, $9,989

(Grant) __University of Oregon__ (Program Grant), [_The Workshop for Environmental Economics and Data Science_](https://tweeds.io), Fall 2019, $2,000

__US EPA EmPOWER Air Data Challenge Winner__ with Meredith Fowlie, _Economic and Environmental Trade-offs Associated with Carbon Mitigation Co-Benefits An Empirical Study Leveraging Declines in Power Plant Emissions and Advances in Data Analytics_, 2019–2020

(Grant) __Private Enterprise Development in Low-Income Countries (PEDL)__ (Exploratory Research Grant) with Erin Kelley, Gregory Lane, and Matthew Pecenco, _Can online marketplaces reduce barriers to growth for small firms?_ 2018–2019, £31,000

Outstanding Graduate-Student Instructor, UC Berkeley, 2018

(Grant) __Private Enterprise Development in Low-Income Countries (PEDL)__ (Exploratory Research Grant) with Erin Kelley and Matthew Pecenco, _The Impact of Consumer-Side Discrimination on Firm Productivity in East Africa_, 2017–2018, £13,000

(Grant) __Giannini Foundation__ (Mini-Grant) with Maximilian Auffhammer, 2017–2018

(Grant) __UC Berkeley__ ARE Summer Grant, 2016

GAANN Fellowship 2013–2015

## Presentations

__2025__: [NBER *The Determinants of Mortality*](https://www.nber.org/conferences/determinants-mortality-spring-2025), [The Occasional Workshop](https://occasionalworkshop.weebly.com/)

__2024__: LEEP (University of Exeter), UCSB Bren, [AERE Annual Summer Conference](https://www.aere.org/assets/2024Conference/aeres_202406_agenda_pdf_jwrno.pdf), Oregon State Policy, [EAERE Summer School](https://eaere-summer-school.uni-graz.at/en/summer-schools-2021-24/), Toulouse School of Economics, Paris School of Economics

__2023__: [EPIC Junior Workshop (UChicago)](https://epic.uchicago.edu/events/event/epic-junior-workshop/)

__2022__: UC Berkeley ARE, GRIPS, Oregon State, EAERE Annual Conference, University of Nebraska–Lincoln

__2021__: AERE Remote Conference, RFF/EPA, CU Environmental & Resource Economics Workshop

__2020__: ASSA Annual Meeting, AERE Remote Conference, Duke Energy Data Analytics Symposium, RFF/EPA

__2019__: Western Economic Association Internation (WEAI) Annual Conference

__2018__: The Occasional Workshop; World Congress of Environmental Economics (WCERE); UC Berkeley, Computational Text Analysis Working Group; University of Oregon, Economics

__2017__: IGC-PEDL Workshop at Oxford; Heartland Environmental and Resource Economics Workshop; Berkeley Development Economics Lunch; Camp Resources; AAEA Annual Meeting; UC Berkeley, Summer Econ. Research Seminar; AERE Annual Summer Conference; 22nd Annual POWER Conference on Energy Research and Policy

__2016__: UC Berkeley, Environmental and Resource Economics Seminar

__2015__: UC Berkeley, Environmental and Resource Economics Seminar

__2013__: University of Nebraska–Lincoln, Statistics Departmental Seminar

__2012__: International Conference of Agricultural Economists (poster)


## Academic service

### Advising

- *PhD committee chair:* Andrew Dickinson (co-chair); Mary Kopriva (Wade) (co-chair); Connor Lennon (co-chair); Emmett Reynier (co-chair); Garrett Stanford (chair)
- *PhD dissertation committee:* Christie Downs (Finance); Claire Lepault (Paris School of Economics); Steven (Marcus) Holloway; Sichao Jiang; Woocheol Kim (Marketing); Kyu Matsuzawa; Robert McDonough; Max Mindock; John Morehouse; Jenni Putz; Meysam Rabiee (Operations and Analytics); Brietta Russell (*in progress*); Steven Walton (Computer Science); Kyle Wilson; Micaela Wood; Dante Yasui (*in progress*)
- *Masters thesis:* Pilar Mullican
- *Undergraduate thesis:* Joseph Andersen (department; advisor), Zoë Arnaut (honors; reader); Eleanor Franks (honors; reader); Lorissa Hughes (*in progress*; chair); Kara Krnacik (honors; chair); Aidan Potts (honors; chair); Sam Schroeder (honors; chair)

### Additional

- Co-founded/Organized [TWEEDS](https://tweeds.io) (The Workshop in Environmental Economics and Data Science)
- Co-founded/Organized [OSWEET](https://edrub.in/osweet) (Online Student Workshop in Environmental, Energy, and Transportation)
- Co-founded/Organized [GoSee](https://gosee.io) (Global Open Series in Environmental Economics)
- Co-organize applied microeconometrics workshop at UO
- **Referee:** [Proceedings of the National Academy of Science (PNAS)](https://www.pnas.org/), [American Economic Review: Insights (AERI)](https://www.aeaweb.org/journals/aeri), [American Economic Journal: Economic Policy](https://www.aeaweb.org/journals/pol) (AEJ Policy), [Journal of the Association of Environmental and Resource Economists](https://www.journals.uchicago.edu/toc/jaere/current) (JAERE), [Journal of Public Economics](https://www.journals.elsevier.com/journal-of-public-economics) (JPubE), [Journal of Health Economics](https://www.sciencedirect.com/journal/journal-of-health-economics) (JHE), [Economic Inquiry](https://onlinelibrary.wiley.com/journal/14657295), [Journal of Environmental Economics and Management](https://www.journals.elsevier.com/journal-of-environmental-economics-and-management) (JEEM), [Land Economics](https://uwpress.wisc.edu/journals/journals/le.html), [Resource and Energy Economics](https://www.journals.elsevier.com/resource-and-energy-economics) (REE), [Energy Policy](https://www.journals.elsevier.com/energy-policy), [Journal of Policy Analysis and Management](http://www.appam.org/jpam/) (JPAM), [Water Economics and Policy](https://www.worldscientific.com/worldscinet/wep) (WEP), [Nature Communications: Earth & Environment](https://www.nature.com/commsenv/), [Economics Letters](https://www.sciencedirect.com/journal/economics-letters)
- **Grant reviewer:** [Alfred P. Sloan Foundation](https://sloan.org/), [Stanford University *Sustainability Accelerator*](https://sustainability-accelerator.stanford.edu/)
- Coordinated Environmental, Energy, and Resource Economics Seminar (UCB)
- Organized biweekly (twice per week) departmental lunches (UCB)
- Organized third-year research workshop (UCB)
- Organized departmental coffee hour (UCB)
- Mentored first-year graduate students (UCB)

## Skills

### Computation

- __Computing:__ R, Python, Stata, Julia, QGIS, MATLAB, Mathematica, SAS
- __Design:__ LaTeX, Markdown, Adobe Suite Design Suite, Microsoft Suite

### Linguistic

- English (fluent)
- Spanish (conversational)

## Contact

- __email__ edwardr `ampersat` uoregon `period` edu
- __website__ [http://edrub.in](https://edrub.in)
- __github__ [edrubin](https://github.com/edrubin)

```{r}
#| include: false
#| echo: false
#| warning: false
#| message: false

source(here::here('cv-script.R'))
```
