---
title: "CV: Edward A. Rubin"
---

[PDF](cvEdRubin.pdf)
<br><br>

## Academic Positions

Assistant Professor, University of Oregon, Department of Economics, 2018–present

<br>

## Education

B.S. Mathematics, University of Nebraska–Lincoln, 2007
<br>M.S. Agricultural Economics, University of Nebraska–Lincoln, 2013
<br>M.S. Statistics, University of Nebraska–Lincoln, 2013
<br>M.S. Agricultural and Resource Economics, UC Berkeley, 2015
<br>Ph.D. Agricultural and Resource Economics, UC Berkeley, 2018
<br>*Committee:* [Maximilian Auffhammer](https://www.auffhammer.com), [Meredith Fowlie](https://www.meredithfowlie.com/), [Reed Walker](https://w-reed-walker.com)

__Primary interests__: Environmental & Energy Economics, Applied Econometrics & Data Science, Inequality & Public Policy
<br>
__Secondary interests__: Health Economics, Development Economics, Criminal Justice

<br>

## Publications

__[Quantifying heterogeneity in the price elasticity of residential natural gas](Papers/draft-natural-gas.pdf)__
<br> Edward Rubin and Maximilian Auffhammer. 2024 (_Forthcoming_). *Journal of the Association of Environmental and Resource Economists*.

__[The Economic Impact of Critical Habitat Designation: Evidence from Vacant-Land Transactions](https://muse.jhu.edu/article/753055)__
<br> Maximilian Auffhammer, Maya Duru, Edward Rubin, and David L. Sunding. 2020. *Land Economics*, 96(2), 188–206.

__[Bringing Satellite-Based Air-Quality Estimates Down to Earth](https://www.aeaweb.org/articles?id=10.1257/pandp.20191064)__
<br> Meredith Fowlie, Edward Rubin, and Reed Walker. 2019. *AEA Papers and Proceedings*, 109: 283-88.

(Book) __[Data Science for Public Policy](https://www.springer.com/gp/book/9783030713515)__ 
<br> Jeffrey Chen, Edward Rubin, and Gary Cornwall. 2021. *Springer*

<br>

## Working Papers

__[Strategic Shutdowns of Air Quality Monitors: Evidence from Jersey City and Across the U.S.](Papers/draft-strategic-monitoring.pdf)__
<br> Yingfei Mu, Edward Rubin, and Eric Zou
<br> _Revise and resubmit_, RESTAT

__[The strategic local geography of US electricity emissions](Papers/draft-plant-locations.pdf)__
<br> John Morehouse and Edward Rubin
<br> _Revise and resubmit_, JAERE

__[What can we machine learn (too much of) in 2SLS? Insights from a bias decomposition](Papers/draft-mliv.pdf)__
<br> Connor Lennon, Edward Rubin, and Glen Waddell

__[Unequal avoidance: Disparities in smoke-induced out-migration](Papers/draft-smoke.pdf)__
<br> M. Steven Holloway and Edward Rubin

__[Customer Discrimination in the Workplace: Evidence from Online Sales](Papers/draft-gender-bias.pdf)__
<br> Erin Kelley, Gregory Lane, Edward Rubin, and Matthew Pecenco

__[When we change the clock, does the clock change us?](https://www.nber.org/papers/w30999)__
<br> Patrick Baylis, Severin Borenstein, and Edward Rubin

__Are our hopes too high? Testing cannabis legalization's potential to reduce criminalization__
<br> Edward Rubin

__[Do aerially applied pesticides affect local air quality? Empirical evidence from California's San Joaquin Valley](Papers/draft-pesticides.pdf)__
<br> Edward Rubin

<br>

## Research in Progress

__Declining power-plant emissions, co-benefits, and regulatory rebound__
<br> Meredith Fowlie, Edward Rubin, and Catherine Wright

__Perinatal health effects of herbicides: Glyphosate, Roundup, and the rollout of GM crops__
<br> Edward Rubin and Emmett Saulnier

__Mismeasurement in exposure and access: Insights from cellphone data__
<br> Edward Rubin

__Interactions between measurement error and policy__
<br> Edward Rubin

__How salient are environmental risks? The short- and long-run effects of lead exposure in piped water__
<br> Edward Rubin

<br>

## Teaching

__[EC607: Econometrics (III): Causal inference](https://github.com/edrubin/EC525S19)__

- University of Oregon: [Spring 2022](https://github.com/edrubin/EC607S22), [Spring 2021](https://github.com/edrubin/EC607S21), [Spring 2020](https://github.com/edrubin/EC607S20), [Spring 2019](https://github.com/edrubin/EC525S19)
- Doctoral level

__[EC524: Econometrics (II): Prediction and machine learning](https://github.com/edrubin/EC524W20)__

- University of Oregon: [Winter 2022](https://github.com/edrubin/EC524W22), [Winter 2021](https://github.com/edrubin/EC524W21), [Winter 2020](https://github.com/edrubin/EC524W20)

__[EC421: Introduction to Econometrics (II)](https://github.com/edrubin/EC421S19)__

- University of Oregon: [Spring 2022](https://github.com/edrubin/EC421S22), [Winter 2022](https://github.com/edrubin/EC421W22), [Winter 2021](https://github.com/edrubin/EC421W21), Spring 2020, [Winter 2020](https://github.com/edrubin/EC421W20), [Spring 2019](https://github.com/edrubin/EC421S19), [Winter 2019](https://github.com/edrubin/EC421W19)
- Undergraduate level

__[ARE 212: Econometrics - Multiple Equation Estimation](https://edrub.in/ARE212)__

- University of California, Berkeley: Spring 2017, Spring 2018
- Doctoral level: taught recitation section and built [section website/notes](http://edrub.in/ARE212/)

__STAT 380: Statistics and Applications__

- University of Nebraska–Lincoln: Summer 2012, Fall 2012, Spring 2013
- Undergraduate level: sole instructor for the course

__STAT 218: Introduction to Statistics__

- University of Nebraska–Lincoln: Spring 2011, Summer 2011, Fall 2011
- Undergraduate level: sole instructor for the course

<br>

## Honors, Awards, and Fellowships

EPA: _A Retrospective Analysis of Indirect Air Quality Benefits from Power-Sector Emissions Reductions_, 2021

Sloan Foundation (for [TWEEDS](https://tweeds.io)), 2020–2022

University of Oregon Data-Science Initiative Seed Funding, 2019–2020

University of Oregon Program Grant, Fall 2019

EPA EmPOWER Air Data Challenge Winner, 2019–2020
<br> _with Meredith Fowlie_

Private Enterprise Development in Low-Income Countries (PEDL) Exploratory Research Grant, 2018–2019
<br> _with Erin Kelley, Gregory Lane, and Matthew Pecenco_

Outstanding Graduate-Student Instructor, UC Berkeley, 2018

Private Enterprise Development in Low-Income Countries (PEDL) Exploratory Research Grant, 2017–2018
<br> _with Erin Kelley and Matthew Pecenco_

Giannini Foundation Mini-Grant, 2017–2018
<br> _with Maximilian Auffhammer_

UC Berkeley ARE Summer Grant, 2016

GAANN Fellowship 2013–2015

<br>

## Presentations

__Power Plants, Air Pollution, and Regulatory Rebound__
<br> EPIC Junior Workshop (University of Chicago), April 2023

__Declining power-plant emissions, co-benefits, and regulatory rebound__
<br> University of Nebraska–Lincoln, November 2022

__What's missing in environmental (self-)monitoring? Evidence from strategic shutdowns of pollution monitors__
<br> Annual Conference of the European Association of Environmental and Resource Economists, June 2022

__Power Plants, Air Pollution, and Regulatory Rebound__
<br> Oregon State University, May 2022

__Power Plants, Air Pollution, and Regulatory Rebound__
<br> National Graduate Institute for Policy Studies (GRIPS), April 2022

__Power Plants, Air Pollution, and Regulatory Rebound__
<br> UC Berkeley ARE, April 2022

__What's missing in environmental (self-)monitoring? Evidence from strategic shutdowns of pollution monitors__
<br> CU Environmental & Resource Economics Workshop, October 2021

__Pollution co-benefits and regulatory rebound__
<br> RFF/EPA, October 2021

__What's missing in environmental (self-)monitoring? Evidence from strategic shutdowns of pollution monitors__
<br> AERE Remote Conference, June 2021

__Downwind and out: The Strategic dispersion of power plants and their pollution__
<br> AERE Remote Conference, June 2021

__A retrospective analysis of indirect air-quality benefits from power-sector emissions reductions__
<br> RFF/EPA (Online), December 2020

__Estimating and decomposing "the" elasticity of demand: Empirical and policy insights from 600 million natural gas bills__
<br> Duke Energy Data Analytics Symposium, December 2020

__Mismeasurement in exposure and access: Insights from cellphone data__
<br> AERE Remote Conference, June 2020

__Declining power-plant emissions, co-benefits, and regulatory rebound__
<br> ASSA Annual Meeting, January 2020

__Mismeasurement in exposure and access: Insights from cellphone data__
<br> Western Economic Association Internation (WEAI) Annual Conference, June 2019

__The economic impact of critical-habitat designation: Evidence from vacant-land transactions__
<br> The Occasional Workshop (UCSB), November 2018

__Natural gas elasticities and optimal cost recovery under heterogeneity: Evidence from 300 million natural gas bills in California__
<br> World Congress of Environmental Economics (WCERE), June 2018

__Is "Michelle" less productive than "Michael"? A field experiment on consumer-based gender discrimination in the marketplace__
<br> UC Berkeley, Computational Text Analysis Working Group, April 2018

__Natural gas elasticities and optimal cost recovery under heterogeneity: Evidence from 300 million natural gas bills in California__
<br> University of Oregon, Economics, February 2018

__Is "Michelle" less productive than "Michael"? A field experiment on consumer-based gender discrimination in the marketplace__
<br> IGC-PEDL Workshop at Oxford, December 2017

__Natural gas elasticities and optimal cost recovery under heterogeneity: Evidence from 300 million natural gas bills in California__
<br> Heartland Environmental and Resource Economics Workshop, September 2017

__Is "Michelle" less productive than "Michael"? A field experiment on consumer-based gender discrimination in the marketplace__
<br> Berkeley Development Economics Lunch, September 2017

__Natural gas elasticities and optimal cost recovery under heterogeneity: Evidence from 300 million natural gas bills in California__
<br> Camp Resources, August 2017

__Natural gas elasticities and optimal cost recovery under heterogeneity: Evidence from 300 million natural gas bills in California__
<br> AAEA Annual Meeting, August 2017

__Do marijuana stores increase or reduce neighborhood crime? Evidence from Denver, Colorado__
<br> UC Berkeley, Summer Research Seminar, July 2017

__Natural gas elasticities and optimal cost recovery under heterogeneity: Evidence from 300 million natural gas bills in California__
<br> AERE Annual Summer Conference, June 2017

__Summertime, and pass-through is easier: Chasing down price elasticities for residential natural gas demand in 275 million bills__
<br> 22nd Annual POWER Conference on Energy Research and Policy, March 2017

__Natural gas elasticities, seasonal heterogeneity, and consumer behavior: Evidence from 300M+ bills__
<br> UC Berkeley, Environmental and Resource Economics Seminar, November 2016

__(Mile-) High Quandaries: Evidence from Denver that Marijuana Legalization May Increase Drug Arrests__
<br> UC Berkeley, Environmental and Resource Economics Seminar, April 2015

__Irrigation and Climatic Effects on Water Levels in the U.S. High Plains Aquifer Along the 41st Parallel in Nebraska (and Several Questions about Model Complexity)__
<br> University of Nebraska–Lincoln, Statistics Departmental Seminar, March 2013

__Irrigation and Climatic Effects on Water Levels in the U.S. High Plains Aquifer__
<br> International Conference of Agricultural Economists, poster, August 2012

<br>

## Academic Service

__Advising__ 

- *PhD committee chair* Mary Kopriva (co-chair); Connor Lennon (co-chair); Garrett Stanford (chair)
- *PhD dissertation committee* Robert McDonough; Max Mindock; John Morehouse; Jenni Putz; Meysam Rabiee; Kyle Wilson; Sichao Zhang
- *Undergraduate* Zoë Arnaut (reader); Eleanor Franks (reader); Kara Krnacik (chair); Aidan Pott (chair)

__Other__

- Co-founded/Organized [TWEEDS](https://tweeds.io) (The Workshop in Environmental Economics and Data Science)
- Co-founded/Organized [OSWEET](https://edrub.in/osweet) (Online Student Workshop in Environmental, Energy, and Transportation)
- Co-founded/Organized [GoSee](https://gosee.io) (Global Open Series in Environmental Economics)
- Co-organize applied microeconometrics workshop at UO
- **Referee:** [American Economic Journal: Economic Policy](https://www.aeaweb.org/journals/pol) (AEJ Policy), [Journal of the Association of Environmental and Resource Economists](https://www.journals.uchicago.edu/toc/jaere/current) (JAERE), [Journal of Public Economics](https://www.journals.elsevier.com/journal-of-public-economics) (JPubE), [Economic Inquiry](https://onlinelibrary.wiley.com/journal/14657295), [Journal of Environmental Economics and Management](https://www.journals.elsevier.com/journal-of-environmental-economics-and-management) (JEEM), [Land Economics](https://uwpress.wisc.edu/journals/journals/le.html), [Resource and Energy Economics](https://www.journals.elsevier.com/resource-and-energy-economics) (REE), [Energy Policy](https://www.journals.elsevier.com/energy-policy), [Journal of Policy Analysis and Management](http://www.appam.org/jpam/) (JPAM), [Water Economics and Policy](https://www.worldscientific.com/worldscinet/wep) (WEP), [Nature Communications: Earth & Environment](https://www.nature.com/commsenv/)
- Coordinated Environmental, Energy, and Resource Economics Seminar (UCB)
- Organized biweekly (twice per week) departmental lunches (UCB)
- Organized third-year research workshop (UCB)
- Organized departmental coffee hour (UCB)
- Mentored first-year graduate students (UCB)

<br>

## Skills

__Computational__

- __Computing:__ R, Python, Stata, Julia, QGIS, MATLAB, Mathematica, SAS
- __Design:__ LaTeX, Markdown, Adobe Suite Design Suite, Microsoft Suite

__Linguistic__

- English (fluent)
- Spanish (conversational)

<br>

## Contact

- __email__ edwardr `ampersat` uoregon `period` edu
- __website__ [http://edrub.in](https://edrub.in)
- __twitter__ [\@edrubin](https://twitter.com/edrubin)
- __instagram__ [\@edwardarubin](https://instagram.com/edwardarubin/)
- __github__ [edrubin](https://github.com/edrubin)
