---
title: "Meetings"
---

A listing of conferences, meetings, and workshops

<br>

### Energy, environmental, and resource economics

- [AAEA Annual Meeting](http://www.aaea.org/meetings) | late July to early August | various locations
- [AERE Annual Summer Conference](http://www.aere.org/aere-summer-conference) | late May to early June | various locations
- [Camp Resources](https://cenrep.ncsu.edu/workshops/camp-resources/) | mid August | Wrightsville Beach, NC
- [Canadian Resource and Environmental Economics Study Group](https://economics.ca/cree/) | late September to early October | various locations
- [Colorado University Environmental and Resource Economics,  Workshop](https://www.colorado.edu/economics/news-events/cu-environmental-resource-economics-workshop) | mid September | Vail, CO
- [EAERE Annual Conference](http://www.eaere.org) | late June | various locations
- [Environmental Economics Workshop at LSE](http://www.lse.ac.uk/Geography-and-Environment/research/environmental-economics-conference-2019) | mid June | London, England
- [Heartland Environmental & Resource Economics (HERE) Workshop at Illinois](http://events.idtg.illinois.edu/here/) | late September | Urbana-Champaign, IL
- [IAEE Conferences](http://www.iaee.org/en/conferences/)
- [JEEM Conference in Environmental and Resource Economics](https://jeemconference.wordpress.com) | late June | various locations
- [Monash Environmental Economics Workshop](https://www.monash.edu/business/news-and-events/events/workshop-third-monash-environmental-economics-workshop) | November or December | Melbourne, Australia
- [The Occasional Workshop](http://www.calworkshop.org) | occasionally in November | Santa Barbara, CA
- [UC Berkeley POWER](https://ei.haas.berkeley.edu/events/power-conference.html) | late March | Berkeley, CA

<br>

### Other meetings of interest

- [ASSA Annual Meeting](https://www.aeaweb.org/conference/) | early January | various locations
- [IAAE Triennial Conference](http://www.iaae-agecon.org/conferences/iaae-triennial-conference) | late July to early August | various locations
- [Young Economist Symposium at Yale](http://economics.yale.edu/graduate/events/yes) (formerly _EconCon_) | mid August | New Haven, CT
