---
title: "Teaching"
---

<head>
<script>
  document.title = "Ed Rubin: Teaching";
</script>
</head>

<!-- <br> -->

# {.tabset .tabset-fade}

## Economics

<br>

__[EC 607](https://github.com/edrubin/EC607S24): PhD Econometrics (III)__
<br> [Spring 2024](https://github.com/edrubin/EC607S24), [Spring 2023](https://github.com/edrubin/EC607S23), [Spring 2022](https://github.com/edrubin/EC607S22), [Spring 2021](https://github.com/edrubin/EC607S21), [Spring 2020](https://github.com/edrubin/EC607S20)
<br> University of Oregon, instructor

<br>

__[EC 524/424](https://github.com/edrubin/EC524S24): Masters Econometrics: Machine Learning and Prediction__
<br> [Spring 2024](https://github.com/edrubin/EC524S24), [Winter 2023](https://github.com/edrubin/EC524W23), [Winter 2022](https://github.com/edrubin/EC524W22), [Winter 2021](https://github.com/edrubin/EC524W21); [Winter 2020](https://github.com/edrubin/EC524W20)
<br> University of Oregon, instructor

<br>

__EAERE Summer School 2024 (Data science in environmental economics research): *Spatial (Data) Science*__
<br> *Slides* [Download via Dropbox](https://www.dropbox.com/scl/fi/up6fmoxcdv0eqmmftrjax/slides-spatial-data.html?rlkey=4s4j2lm8039x1gotqgjgqoxg3&dl=0) | [View online](https://rawcdn.githack.com/edrubin/edrubin.github.io/bcc75318e3f6a482b2da4060374622bf2bb138e4/Slides/slides-spatial-data.html?min=1)
<br> *Warning:* Slides are a bit big (92MB).

<br>

__[EC 525/425](https://github.com/edrubin/EC525S19): PhD Econometrics (III)__
<br> [Spring 2019](https://github.com/edrubin/EC525S19)
<br> University of Oregon, instructor

<br>

__[EC 421](https://github.com/edrubin/EC421W19): Introduction to Econometrics (II)__
<br> Spring 2023, Winter 2023,, Spring 2022, Winter 2022, [Winter 2021](https://github.com/edrubin/EC421W21); [Spring 2020](https://github.com/edrubin/EC421S20); [Winter 2020](https://github.com/edrubin/EC421W20); [Spring 2019](https://github.com/edrubin/EC421S19); [Winter 2019](https://github.com/edrubin/EC421W19)
<br> University of Oregon, instructor

<br>

__[ARE 212](https://edrub.in/ARE212): Econometrics - Multiple Equation Estimation__
<br> [Spring 2017](https://edrub.in/ARE212/Spring2017/notes.html); [Spring 2018](https://edrub.in/ARE212)
<br> UC Berkeley, GSI for [Dr. Maximilian Auffhammer](http://www.auffhammer.com)


## Statistics

__STAT/MATH 218: Introduction to Statistics__
<br> Spring 2011; Summer 2011; Fall 2011
<br> University of Nebraska—Lincoln, sole instructor

<br>

__STAT/MATH 380: Statistics and Applications__
<br> Summer 2012; Fall 2012; Spring 2013
<br> University of Nebraska—Lincoln, sole instructor
